[project]
name = "deepseek-engineer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.58.1",
    "prompt-toolkit>=3.0.50",
    "pydantic>=2.10.4",
    "python-dotenv>=1.0.1",
    "rich>=13.9.4",
]

[project.scripts]
deepseek-engineer = "deepseek_engineer_entrypoint:main"

[tool.setuptools]
include-package-data = true
[tool.setuptools.package-data]
